# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my_proto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emy_proto.proto\x12\tone_scout\"\x9e\x04\n\x04game\x12\x18\n\x0bteam_number\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04\x63omp\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x12\n\x05round\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x1b\n\x0e\x61lliance_color\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x18\n\x0bintake_auto\x18\x05 \x01(\x05H\x04\x88\x01\x01\x12\x18\n\x0b\x62ottom_auto\x18\x06 \x01(\x05H\x05\x88\x01\x01\x12\x15\n\x08top_auto\x18\x07 \x01(\x05H\x06\x88\x01\x01\x12\x18\n\x0bintake_tele\x18\x08 \x01(\x05H\x07\x88\x01\x01\x12\x18\n\x0b\x62ottom_tele\x18\t \x01(\x05H\x08\x88\x01\x01\x12\x15\n\x08top_tele\x18\n \x01(\x05H\t\x88\x01\x01\x12\x18\n\x0b\x63limb_level\x18\x0b \x01(\x05H\n\x88\x01\x01\x12\x14\n\x07\x64riving\x18\x0c \x01(\x05H\x0b\x88\x01\x01\x12\x14\n\x07\x64\x65\x66\x65nse\x18\r \x01(\x05H\x0c\x88\x01\x01\x12\x16\n\tfree_text\x18\x0e \x01(\tH\r\x88\x01\x01\x42\x0e\n\x0c_team_numberB\x07\n\x05_compB\x08\n\x06_roundB\x11\n\x0f_alliance_colorB\x0e\n\x0c_intake_autoB\x0e\n\x0c_bottom_autoB\x0b\n\t_top_autoB\x0e\n\x0c_intake_teleB\x0e\n\x0c_bottom_teleB\x0b\n\t_top_teleB\x0e\n\x0c_climb_levelB\n\n\x08_drivingB\n\n\x08_defenseB\x0c\n\n_free_textb\x06proto3')



_GAME = DESCRIPTOR.message_types_by_name['game']
game = _reflection.GeneratedProtocolMessageType('game', (_message.Message,), {
  'DESCRIPTOR' : _GAME,
  '__module__' : 'my_proto_pb2'
  # @@protoc_insertion_point(class_scope:one_scout.game)
  })
_sym_db.RegisterMessage(game)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GAME._serialized_start=30
  _GAME._serialized_end=572
# @@protoc_insertion_point(module_scope)
