# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my_proto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emy_proto.proto\x12\tone_scout\"\x86\x01\n\x04game\x12\x18\n\x0bteam_number\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x19\n\x0cnum_of_balls\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x18\n\x0b\x63limb_level\x18\x03 \x01(\tH\x02\x88\x01\x01\x42\x0e\n\x0c_team_numberB\x0f\n\r_num_of_ballsB\x0e\n\x0c_climb_levelb\x06proto3')



_GAME = DESCRIPTOR.message_types_by_name['game']
game = _reflection.GeneratedProtocolMessageType('game', (_message.Message,), {
  'DESCRIPTOR' : _GAME,
  '__module__' : 'my_proto_pb2'
  # @@protoc_insertion_point(class_scope:one_scout.game)
  })
_sym_db.RegisterMessage(game)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GAME._serialized_start=30
  _GAME._serialized_end=164
# @@protoc_insertion_point(module_scope)
