export const POINTS_ADDED = 'POINTS_ADDED';
export const POINTS_DEDUCTED = 'POINTS_DEDUCTED';

export const COMP_NAME_SET = 'COMP_NAME_SET';
export const ROUND_NAME_SET = 'ROUND_NAME_SET';
export const TEAM_NAME_SET = 'TEAM_NAME_SET';