import { StyleSheet } from "react-native";

export default styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: '#882',
		alignItems: 'center',
		justifyContent: 'flex-start',
	},
	header: {
		flex: 0.2,
		width: '100%',
		backgroundColor: '#0a0',
		alignItems: 'flex-end',
		justifyContent: 'flex-start',
		textAlign: 'center',
		textAlignVertical: "center",
		fontWeight: 'bold',
		fontSize: 25,
		marginTop: 0,
	},
	topMenu: {
		flex: 1,
		width: '100%',
		backgroundColor: '#aaa',
		alignItems: 'flex-end',
		justifyContent: 'flex-start',
		textAlign: 'center',
		textAlignVertical: "center",
		fontWeight: 'bold',
		fontSize: 25,
		marginTop: 0,
	},
	bottomMenu: {
		flex: 1,
		width: '100%',
		backgroundColor: '#aaa',
		alignItems: 'flex-end',
		justifyContent: 'flex-start',
		textAlign: 'center',
		textAlignVertical: "center",
		fontWeight: 'bold',
		fontSize: 25,
		marginTop: 0,
	},
	bigText: {
		textAlign: 'center',
		textAlignVertical: "center",
		fontWeight: 'bold',
		fontSize: 100,
	},
	button: {
		flex: 0.4,
		backgroundColor: 'indigo',
		alignItems: 'center',
		justifyContent: 'center',
	},
	border: {
		flex: 0.025,
		backgroundColor: '#000',
	},
	top: {
		flex: 5,
		width: '100%',
		backgroundColor: 'ivory',
		alignItems: 'center',
		justifyContent: 'flex-start',
	},
	bottom: {
		flex: 5,
		width: '100%',
		backgroundColor: 'khaki',
		alignItems: 'center',
		justifyContent: 'flex-start',
	},
});
