// source: my_proto.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

goog.exportSymbol('proto.one_scout.game', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.one_scout.game = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.one_scout.game, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.one_scout.game.displayName = 'proto.one_scout.game';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.one_scout.game.prototype.toObject = function(opt_includeInstance) {
  return proto.one_scout.game.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.one_scout.game} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.one_scout.game.toObject = function(includeInstance, msg) {
  var f, obj = {
    teamNumber: jspb.Message.getFieldWithDefault(msg, 1, ""),
    comp: jspb.Message.getFieldWithDefault(msg, 2, ""),
    round: jspb.Message.getFieldWithDefault(msg, 3, ""),
    allianceColor: jspb.Message.getFieldWithDefault(msg, 4, ""),
    intakeAuto: jspb.Message.getFieldWithDefault(msg, 5, 0),
    bottomAuto: jspb.Message.getFieldWithDefault(msg, 6, 0),
    topAuto: jspb.Message.getFieldWithDefault(msg, 7, 0),
    intakeTele: jspb.Message.getFieldWithDefault(msg, 8, 0),
    bottomTele: jspb.Message.getFieldWithDefault(msg, 9, 0),
    topTele: jspb.Message.getFieldWithDefault(msg, 10, 0),
    climbLevel: jspb.Message.getFieldWithDefault(msg, 11, 0),
    driving: jspb.Message.getFieldWithDefault(msg, 12, 0),
    defense: jspb.Message.getFieldWithDefault(msg, 13, 0),
    freeText: jspb.Message.getFieldWithDefault(msg, 14, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.one_scout.game}
 */
proto.one_scout.game.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.one_scout.game;
  return proto.one_scout.game.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.one_scout.game} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.one_scout.game}
 */
proto.one_scout.game.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTeamNumber(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setComp(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRound(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setAllianceColor(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIntakeAuto(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBottomAuto(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTopAuto(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIntakeTele(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBottomTele(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTopTele(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setClimbLevel(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDriving(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDefense(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setFreeText(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.one_scout.game.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.one_scout.game.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.one_scout.game} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.one_scout.game.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 11));
  if (f != null) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 12));
  if (f != null) {
    writer.writeInt32(
      12,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 13));
  if (f != null) {
    writer.writeInt32(
      13,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 14));
  if (f != null) {
    writer.writeString(
      14,
      f
    );
  }
};


/**
 * optional string team_number = 1;
 * @return {string}
 */
proto.one_scout.game.prototype.getTeamNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.setTeamNumber = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.clearTeamNumber = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.one_scout.game.prototype.hasTeamNumber = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string comp = 2;
 * @return {string}
 */
proto.one_scout.game.prototype.getComp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.setComp = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.clearComp = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.one_scout.game.prototype.hasComp = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string round = 3;
 * @return {string}
 */
proto.one_scout.game.prototype.getRound = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.setRound = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.clearRound = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.one_scout.game.prototype.hasRound = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string alliance_color = 4;
 * @return {string}
 */
proto.one_scout.game.prototype.getAllianceColor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.setAllianceColor = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.clearAllianceColor = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.one_scout.game.prototype.hasAllianceColor = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional int32 intake_auto = 5;
 * @return {number}
 */
proto.one_scout.game.prototype.getIntakeAuto = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.setIntakeAuto = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.clearIntakeAuto = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.one_scout.game.prototype.hasIntakeAuto = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional int32 bottom_auto = 6;
 * @return {number}
 */
proto.one_scout.game.prototype.getBottomAuto = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.setBottomAuto = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.clearBottomAuto = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.one_scout.game.prototype.hasBottomAuto = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional int32 top_auto = 7;
 * @return {number}
 */
proto.one_scout.game.prototype.getTopAuto = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.setTopAuto = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.clearTopAuto = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.one_scout.game.prototype.hasTopAuto = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional int32 intake_tele = 8;
 * @return {number}
 */
proto.one_scout.game.prototype.getIntakeTele = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.setIntakeTele = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.clearIntakeTele = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.one_scout.game.prototype.hasIntakeTele = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional int32 bottom_tele = 9;
 * @return {number}
 */
proto.one_scout.game.prototype.getBottomTele = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.setBottomTele = function(value) {
  return jspb.Message.setField(this, 9, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.clearBottomTele = function() {
  return jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.one_scout.game.prototype.hasBottomTele = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional int32 top_tele = 10;
 * @return {number}
 */
proto.one_scout.game.prototype.getTopTele = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.setTopTele = function(value) {
  return jspb.Message.setField(this, 10, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.clearTopTele = function() {
  return jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.one_scout.game.prototype.hasTopTele = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional int32 climb_level = 11;
 * @return {number}
 */
proto.one_scout.game.prototype.getClimbLevel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.setClimbLevel = function(value) {
  return jspb.Message.setField(this, 11, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.clearClimbLevel = function() {
  return jspb.Message.setField(this, 11, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.one_scout.game.prototype.hasClimbLevel = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional int32 driving = 12;
 * @return {number}
 */
proto.one_scout.game.prototype.getDriving = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.setDriving = function(value) {
  return jspb.Message.setField(this, 12, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.clearDriving = function() {
  return jspb.Message.setField(this, 12, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.one_scout.game.prototype.hasDriving = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional int32 defense = 13;
 * @return {number}
 */
proto.one_scout.game.prototype.getDefense = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.setDefense = function(value) {
  return jspb.Message.setField(this, 13, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.clearDefense = function() {
  return jspb.Message.setField(this, 13, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.one_scout.game.prototype.hasDefense = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional string free_text = 14;
 * @return {string}
 */
proto.one_scout.game.prototype.getFreeText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.setFreeText = function(value) {
  return jspb.Message.setField(this, 14, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.one_scout.game} returns this
 */
proto.one_scout.game.prototype.clearFreeText = function() {
  return jspb.Message.setField(this, 14, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.one_scout.game.prototype.hasFreeText = function() {
  return jspb.Message.getField(this, 14) != null;
};


goog.object.extend(exports, proto.one_scout);
